CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	password_hash varchar(64) NOT NULL,
	username varchar(64) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE public.tasks (
	author_id int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	recipient_id int8 NOT NULL,
	"text" varchar(255) NOT NULL,
	CONSTRAINT tasks_pkey PRIMARY KEY (id),
	CONSTRAINT tasks_author_id_fk FOREIGN KEY (author_id) REFERENCES public.users(id),
	CONSTRAINT tasks_recipient_id_fk FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
